const mongoose = require('mongoose');

// Define the schema for documents
const documentSchema = new mongoose.Schema({
  // The user who uploaded the document
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'studentModel', 
    required: true,
  },
  // Original file name
  originalName: {
    type: String,
    required: true,
  },
  // Stored file name (generated by multer or a unique identifier)
  storedName: {
    type: String,
    required: true,
  },
  // File type (e.g., 'pdf', 'docx', 'jpg')
  fileType: {
    type: String,
    required: true,
  },
  // Date and time of upload
  uploadedAt: {
    type: Date,
    default: Date.now,
  },
});

// Create the Document model
const Document = mongoose.model('Document', documentSchema);

module.exports = Document;
